### ISSUE TITLE
FTP poll directory

### ISSUE THREAD

**Issue by dchitra33** [drapostolos/rdp4j#1]
how to poll multiple directories parlell at different time intervals in java file monitoring?
I have set default time interval for multiple Diectories using setPollingInterval(30, TimeUnit.SECONDS).
I want to set different time intervals for different directories .Is it possible?

**Comment by AjayDevasahayam** [comment]
Nice one! thanks for your works Indeed a timely help !! , As a small suggestion to your Grt Work , Why didn't you add "port" field in FtpDirectory.class(since I'm using specific port, I added manually )
