### ISSUE TITLE
Tracking last file?

### ISSUE THREAD

**Issue by javadevmtl** [drapostolos/rdp4j#23]
Hi does rdp4j track the position of where it left off? For example if the app stops or is restarted how does it know which is the next file to read?

**Comment by drapostolos** [comment]
Hi. There is currently no such thing. There is an older issue (#10), which could be the beginning of such feature.

How would you like such feature to look like? I'm happy to discuss this further.

**Comment by drapostolos** [comment]
similar issue as in #2

**Comment by drapostolos** [comment]
This has been fixed in version [0.3.0 ](https://github.com/drapostolos/rdp4j/releases/tag/rdp4j-0.3.0)
