### ISSUE TITLE
Add a port field

### ISSUE THREAD

**Issue by AjayDevasahayam** [drapostolos/rdp4j#4]
@drapostolos  Nice one! thanks for your works Indeed a timely help !! , As a small suggestion to your Grt Work , Why didn't you add "port" field in FtpDirectory.class(since I'm using specific port, I added manually ) 

I'm facing an issue of not being notified when a file  is changed in remote loc  more than 2 times inside the polled directory.... : (  pls post any work around ..Thanks in advance!!

**Comment by drapostolos** [comment]
Thanks for the feedback :)

The `FtpDirectory` example, is just an example. I tried to keep the example as short as possible just to give an idea how the rdp4j library can be used. How about adding `FtpDirectory` (using apache Ftp client ) implementation as a separate library? Would you find that useful?

I'm not sure I understand your issue, could you please describe it in more detail? and preferable in a separate issue (to keep separate issues apart.).

/Alex

**Comment by AjayDevasahayam** [comment]
I think I misunderstood  the thread calling and sleeping methods
DirectoryPoller dp = DirectoryPoller.newBuilder()
            .addPolledDirectory(polledDirectory)
            .addListener(new MyListener())
            .enableFileAddedEventsForInitialContent()
            .setPollingInterval(4, TimeUnit.SECONDS)//   assume as t1= 4 secs
            .start();


        TimeUnit.HOURS.sleep(2);// t2 = 2 hrs

Above is your code ,
Here are my understandings :
1) here directory poller thread checks for any poll in the listeners  for every t1 secs ,Am I right?
2) this thread  will be executing for 2 hours of duration

Please correct me If I'm wrong. @drapostolos I think this may solve my prob.

cheers
Ajay

**Comment by drapostolos** [comment]
This part is just there as an example:
`TimeUnit.HOURS.sleep(2);`
It is meant for your application to do whatever it does, until something triggers it to shut down. Then you call `dp.stop`

You are correct, your code snipped will ask the FTP server for the content of the PolledDirectory every 4th second. The current content is then compared with previous content.

The `FileElementCacher` class holds a snapshot view of the lastModified date for the file, so it can be used when comparing it with the next coming poll. If `lastModified()` method returns a "live" date for each call, then it would not be possible to use the value to compare with the value from the previous or next poll.

Regarding the `Thread [pool-1-thread-1] (Running) `:
I'm not sure what that is. I will have a look at it. 
I'm internally using the `java.util.concurrent.Executors.newSingleThreadExecutor()` when polling Directories sequentially. It might be the case that this executor keeps its working thread running in idle mode.

**Comment by drapostolos** [comment]
Seems this is a bug: `Thread [pool-1-thread-1] (Running):`

Will fix this in next release. Thanks for reporting it.

**Comment by drapostolos** [comment]
Created a new issue for the bug (See issue #7) and closing this.
