### ISSUE TITLE
why didn't you add 'FtpDirectory' to the library?

### ISSUE THREAD

**Issue by OhadR** [drapostolos/rdp4j#6]
i suggest to add 'impl' package, and put there all implementations, such as FtpDirectory, JavaIoFileAdapter, etc. This way users can use your jar with all built-in impl's.

great work, BTW!!!

**Comment by drapostolos** [comment]
Thanks for the comment :)

I didn't add the `FtpDirectory` on purpose, as it depends on the  apache commons-net FtpClient and not all users needs this dependency.

However, I have been thinking of adding sub-projects with different real implementations. I will do that as soon as get the time.

/Alex

**Comment by OhadR** [comment]
BTW, if you show example for FTP, I can share example for SFTP...

**Comment by drapostolos** [comment]
yes, please share :)

**Comment by OhadR** [comment]
https://github.com/OhadR/rdp4j-client/tree/master/src/main/java/example/sftp

**Comment by drapostolos** [comment]
Thanks @OhadR !

Just updated the User Guide with a link to your examples :+1:

**Comment by drapostolos** [comment]
See: https://github.com/drapostolos/rdp4j/wiki/User-Guide#sftpolleddirectory

**Comment by OhadR** [comment]
you are welcome, @drapostolos ! you code project is great and helped me a lot.
One comment: in your wiki, you wrote (the header): SftPolledDirectory. I'd changed that to SftpPolledDirectory (missing p...)

**Comment by drapostolos** [comment]
added the missing p.
